### PR TITLE
Remove chrome command API related code.

### PR DESCRIPTION
**Pull request by sunglim**
@ayhankuru  I'm going to ban chrome.command API related code until you explain why we need it.

### CODE REVIEW

**Comment by ayhankuru** [comment]
@sunglim auto-repeat is turned off, the keyboard should be able to start repeating.I'm using this for myself and keyboard events ```chrome.commands``` and ``chrome.tabs`` need :(

**Comment by sunglim** [comment]
I see. I'll add it back again. (But it looks like a small refactoring might be needed.)
Thank you for the explanation.

**Comment by ayhankuru** [comment]
@sunglim sorry, my code spaghetti refactor needed

**Comment by sunglim** [comment]
all right :) I'll add code and upload to webstore today.

**Pull request merged**
